name:                advent-of-code
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/advent-of-code#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2024 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 10
  - classy-prelude >= 1.5 && < 2

  - array
  - attoparsec
  - either
  - file-embed
  - microlens
  - microlens-th
  - random
  - text
  - uuid

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  automated-tests:
    main:                Spec.hs
    source-dirs:         test/automated
    dependencies:
      - advent-of-code
      - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

